# Generated by Django 4.0.4 on 2022-04-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0002_contactlist_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='additional1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='additional2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
