# Generated by Django 4.0.4 on 2022-04-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0006_alter_campaign_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='message',
            field=models.TextField(),
        ),
    ]
