# Generated by Django 4.0.4 on 2022-05-01 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0007_alter_campaign_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='cost',
            field=models.CharField(default='MWK 0.0000', max_length=13),
        ),
        migrations.AddField(
            model_name='campaign',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=16),
            preserve_default=False,
        ),
    ]
