# Generated by Django 4.0.4 on 2022-05-07 23:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0010_alter_campaignlist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlist',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaignlist',
            name='date_scheduled',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaignlist',
            name='list_name',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='smsApp.contactlist'),
        ),
        migrations.AddField(
            model_name='campaignlist',
            name='message',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaignlist',
            name='title',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
