# Generated by Django 4.0.4 on 2022-05-07 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0011_campaignlist_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='list_name',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='smsApp.contactlist'),
        ),
    ]
